name: Document GitHub action

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/media.yml"
      - ".github/workflows/documentation.yml"
      - "action.yml"
      - "package.json"
      - "README.md"

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Write documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Documentation action
        id: documentation
        uses: katydecorah/documentation-action@v1.5.0
        with:
          example-workflow-file: "media.yml"
          additional-workflow-file-prefix: "media"
      - name: Commit files
        if: steps.documentation.outputs.update == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update documentation"
          git push
